import { Badge } from "@/components/ui/badge";

const Index = () => {
  return (
    <div className="min-h-screen bg-background py-8 px-4 md:py-12 md:px-8 lg:px-16">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <header className="mb-8 md:mb-12">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground leading-tight">
            Detecting AI-Generated Images
          </h1>
          <h2 className="text-2xl md:text-3xl lg:text-4xl font-light text-primary mt-1">
            using color distribution
          </h2>
          <p className="text-muted-foreground mt-4 max-w-2xl text-base md:text-lg">
            A simple idea: if we gently disturb colors, real photos stay stable — AI-generated images break more.
          </p>
          
          {/* Tags */}
          <div className="flex flex-wrap gap-2 mt-6">
            <Badge variant="outline" className="text-sm">GANs</Badge>
            <Badge variant="outline" className="text-sm">Diffusion Models</Badge>
            <Badge variant="outline" className="text-sm">Color Distribution</Badge>
            <Badge variant="outline" className="text-sm">Fast + Lightweight</Badge>
          </div>
        </header>

        {/* Main Content Grid */}
        <div className="grid md:grid-cols-2 gap-6 lg:gap-8">
          {/* Left Column */}
          <div className="space-y-6">
            {/* Introduction Card */}
            <section className="poster-card">
              <h3 className="poster-heading">Introduction</h3>
              <ul className="poster-list">
                <li>AI can now create very realistic images.</li>
                <li>These images are generated by AI models, not taken by a camera.</li>
                <li>This matters because fake images can be used for misinformation, fraud, or identity theft.</li>
              </ul>
            </section>

            {/* Types of AI Card */}
            <section className="poster-card">
              <h3 className="poster-heading">Two types of image-generating AI</h3>
              <ul className="poster-list">
                <li>
                  <strong>Generative Adversarial Networks (GANs):</strong> two AIs compete—one creates images, the other checks if they look real.
                </li>
                <li>
                  <strong>Diffusion models:</strong> start from random noise and refine it step by step into an image.
                </li>
              </ul>
            </section>

            {/* Problem Card */}
            <section className="poster-card">
              <h3 className="poster-heading">Why existing detectors struggle</h3>
              <ul className="poster-list">
                <li>Many methods work on older generators, but fail on new ones.</li>
                <li>Most look at content or style, so performance drops when the style changes (photos vs artwork).</li>
              </ul>
            </section>

            {/* Key Observation - Highlighted */}
            <section className="poster-card-highlight">
              <h3 className="poster-heading text-highlight-foreground">Key observation</h3>
              <ul className="poster-list-highlight">
                <li>AI-generated images often have stronger, more uneven color distributions.</li>
                <li>Real photos usually look smoother and more balanced due to camera color correction.</li>
              </ul>
            </section>
          </div>

          {/* Right Column */}
          <div className="space-y-6">
            {/* Method Card */}
            <section className="poster-card">
              <h3 className="poster-heading">Method in one view</h3>
              <div className="space-y-4 mt-4">
                <div className="method-step">
                  <span className="method-number">01</span>
                  <div>
                    <p className="font-semibold text-foreground">Quantize colors</p>
                    <p className="text-muted-foreground text-sm">Reduce color precision to expose instability.</p>
                  </div>
                </div>
                <div className="method-step">
                  <span className="method-number">02</span>
                  <div>
                    <p className="font-semibold text-foreground">Add tiny noise</p>
                    <p className="text-muted-foreground text-sm">Repeat with small random perturbations.</p>
                  </div>
                </div>
                <div className="method-step">
                  <span className="method-number">03</span>
                  <div>
                    <p className="font-semibold text-foreground">Restore by averaging</p>
                    <p className="text-muted-foreground text-sm">Average noisy copies to reconstruct.</p>
                  </div>
                </div>
                <div className="method-step">
                  <span className="method-number">04</span>
                  <div>
                    <p className="font-semibold text-foreground">Measure color change</p>
                    <p className="text-muted-foreground text-sm">AI images shift more than real photos.</p>
                  </div>
                </div>
              </div>

              {/* Memory Trick */}
              <div className="memory-trick">
                <p className="font-semibold text-sm text-memory-foreground mb-1">Memory trick</p>
                <p className="text-sm text-memory-foreground/80">
                  AI images look colorful → we disturb the colors → AI images break more.
                </p>
              </div>
            </section>

            {/* Results Card */}
            <section className="poster-card">
              <h3 className="poster-heading">Results & takeaways</h3>
              <div className="space-y-4 mt-4">
                <div className="result-item">
                  <span className="text-xs text-muted-foreground uppercase tracking-wide">Model</span>
                  <p className="font-semibold text-lg text-foreground">Lightweight + fast</p>
                </div>
                <div className="result-item">
                  <span className="text-xs text-muted-foreground uppercase tracking-wide">Generalization</span>
                  <p className="font-semibold text-lg text-foreground">Strong on new generators</p>
                </div>
                <div className="result-item">
                  <span className="text-xs text-muted-foreground uppercase tracking-wide">Style shift</span>
                  <p className="font-semibold text-lg text-foreground">Better on artwork datasets</p>
                </div>
              </div>
            </section>

            {/* Conclusion Card */}
            <section className="poster-card border-l-4 border-l-primary">
              <h3 className="poster-heading">Conclusion</h3>
              <p className="text-muted-foreground leading-relaxed">
                Color distribution is a reliable and efficient indicator for detecting AI-generated images — even when other methods fail on new generators or different image styles.
              </p>
              <p className="mt-4 text-foreground font-medium">
                Thank you for listening. Happy to answer questions!
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Index;
